artifacts_root: artifacts

data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/AliTheAnalyst01/Machine-Learning-End-to-End-Project/blob/main/WineQT.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion 
