artifacts_root: artifacts

data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/AliTheAnalyst01/Machine-Learning-End-to-End-Project/raw/refs/heads/main/WineQT.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/unzipped_data  # Ensure this matches the directory where the CSV is extracted

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  unzip_data_dir: artifacts/data_ingestion/unzipped_data/data.csv  # Ensure this matches the extracted file path
