artifacts_root: artifacts

data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/AliTheAnalyst01/livesensor/raw/refs/heads/main/WineQT.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/unzipped_data  # Ensure this matches the directory where the CSV is extracted

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  unzip_data_dir: artifacts/data_ingestion/unzipped_data/WineQT.csv # Ensure this matches the extracted file path


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/unzipped_data/WineQT.csv


model_trainer: 
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib



model_evalution:
  root_dir: artifacts/model_evalution
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evalution/metrics.json